[package]
name = "rapier_overlay"
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false }
rapier3d-f64 = { version = "0.18.0", features = ["serde", "simd-stable"] }
