[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
# lto = "fat"
debug = true
strip = false

[workspace]
resolver = "2"

members = [
  "svo",
  "erionite",
  "utils",
]
