[package]
name = "erionite"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.1"
noise = "0.9.0"
ordered-float = "4.2.0"
rand = { version = "0.8.5", features = ["small_rng"] }
svo = { version = "0.1.0", path = "../svo" }
utils = { version = "0.1.0", path = "../utils" }
